services:
  user-db:
    image: postgres:16-alpine
    container_name: sio-user-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sio-user-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - user-internal
    restart: unless-stopped

  user-service:
    image: faizms14/sio-user-service:latest
    container_name: sio-user-service
    env_file:
      - .env
    networks:
      - user-internal
      - sio-net
      - proxy_net
    depends_on:
      user-db:
        condition: service_healthy

    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy_net
      traefik.http.routers.sio-user.rule: "Host(`sioms.faizms.com`) && (PathPrefix(`/auth`) || PathPrefix(`/users`))"
      traefik.http.routers.sio-user.entrypoints: websecure
      traefik.http.routers.sio-user.tls: "true"
      traefik.http.routers.sio-user.tls.certresolver: myresolver
      traefik.http.services.sio-user.loadbalancer.server.port: "3001"
      traefik.http.middlewares.sio-user-middleware.stripprefix.prefixes: /auth
      traefik.http.routers.sio-user.middlewares: sio-user-middleware

    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: sio-user-adminer
    # ports:
    #   - "8081:8080"
    depends_on:
      - user-db
    networks:
      - sio-net

volumes:
  sio-user-db-data:

networks:
  user-internal:
    name: sio-user-internal
  sio-net:
    external: true
  proxy_net:
    external: true


